# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AppStats(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, stats: object=None):  # noqa: E501
        """AppStats - a model defined in Swagger

        :param stats: The stats of this AppStats.  # noqa: E501
        :type stats: object
        """
        self.swagger_types = {
            'stats': object
        }

        self.attribute_map = {
            'stats': 'stats'
        }
        self._stats = stats

    @classmethod
    def from_dict(cls, dikt) -> 'AppStats':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppStats of this AppStats.  # noqa: E501
        :rtype: AppStats
        """
        return util.deserialize_model(dikt, cls)

    @property
    def stats(self) -> object:
        """Gets the stats of this AppStats.


        :return: The stats of this AppStats.
        :rtype: object
        """
        return self._stats

    @stats.setter
    def stats(self, stats: object):
        """Sets the stats of this AppStats.


        :param stats: The stats of this AppStats.
        :type stats: object
        """

        self._stats = stats
