# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class AppTarget(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    PC = "PC"
    BOARD = "Board"
    ALL = "All"
    def __init__(self):  # noqa: E501
        """AppTarget - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'AppTarget':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppTarget of this AppTarget.  # noqa: E501
        :rtype: AppTarget
        """
        return util.deserialize_model(dikt, cls)
